# Generated by Django 4.1.7 on 2023-05-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_categoria_alter_producto_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='empresa',
            new_name='empresa_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='marca_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='talla',
            new_name='talla_id',
        ),
    ]
