# Generated by Django 4.1.7 on 2023-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_categoria_producto_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='producto'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
