# Generated by Django 4.2.1 on 2023-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(default='sinimagen.png', max_length=50)),
                ('promocion', models.IntegerField(choices=[(0, 'Normal'), (1, 'Promoción (categoria del mes)')], default=1)),
                ('fecha', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=0)),
                ('idEmpresa', models.CharField(max_length=100)),
            ],
        ),
    ]
