# Generated by Django 4.1.7 on 2023-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='categoria'),
        ),
    ]
