# Generated by Django 4.1.7 on 2023-05-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_empresa_direccion_alter_empresa_email_and_more'),
        ('categories', '0002_alter_categorias_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='idEmpresa',
        ),
        migrations.AddField(
            model_name='categorias',
            name='empresa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
