# Generated by Django 4.1.7 on 2023-05-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('logo1', models.CharField(max_length=50)),
                ('logo2', models.CharField(max_length=50)),
                ('logo3', models.CharField(max_length=50)),
                ('logo4', models.CharField(max_length=50)),
                ('logo5', models.CharField(max_length=50)),
                ('logo6', models.CharField(max_length=50)),
                ('logo7', models.CharField(max_length=50)),
                ('logo8', models.CharField(max_length=50)),
                ('logo9', models.CharField(max_length=50)),
                ('logo10', models.CharField(max_length=50)),
                ('logo11', models.CharField(max_length=50)),
                ('logo12', models.CharField(max_length=50)),
                ('mostrarMarcas', models.IntegerField(choices=[(1, 'Mostrar'), (0, 'Ocultar')], default=1)),
                ('fecha', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
    ]
