# Generated by Django 4.1.7 on 2023-05-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0003_rename_empresa_marca_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='empresa_Id',
            new_name='empresa_id',
        ),
    ]
