# Generated by Django 4.1.7 on 2023-05-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0006_alter_marca_logo1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='logo1',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo10',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo11',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo12',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo2',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo3',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo4',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo5',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo6',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo7',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo8',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo9',
        ),
    ]
