# Generated by Django 4.2.1 on 2023-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=17)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('imagen', models.CharField(default='sinimagen.png', max_length=50)),
                ('favicon', models.CharField(blank=True, max_length=50, null=True)),
                ('tituloPagina', models.CharField(default='Carrito de compra', max_length=100)),
                ('ruta', models.CharField(default='http://gustabin.com/ecommerce/img/', max_length=150)),
                ('subdominio', models.CharField(blank=True, max_length=100, null=True)),
                ('apodo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo1', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo2', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo3', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo1', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitulo2', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitulo3', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion1', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion2', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion3', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen1', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen3', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(default='Sin direccion', max_length=100)),
                ('gateway', models.IntegerField(choices=[(0, 'paypal'), (1, 'Mercadolibre'), (2, 'stripe')], default=0)),
                ('environment', models.IntegerField(choices=[(0, 'sandbox'), (1, 'production')], default=0)),
                ('sandbox', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('produccion', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('secret', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('accessToken', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('publicaStripe', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('secretaStripe', models.CharField(blank=True, default='', max_length=110, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=0)),
            ],
        ),
    ]
