# Generated by Django 4.1.7 on 2023-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='imagen',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen1',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen2',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen3',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='empresa'),
        ),
    ]
