# Generated by Django 4.1.7 on 2023-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_empresa_imagen_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='favicon',
            field=models.CharField(blank=True, default='sinimagen.png', max_length=50, null=True),
        ),
    ]
