# Generated by Django 4.1.7 on 2023-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='favicon',
            field=models.ImageField(blank=True, default='sinimagen.png', null=True, upload_to='empresa'),
        ),
    ]
