# Generated by Django 4.1.7 on 2023-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empresa_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
