# Generated by Django 4.1.7 on 2023-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_empresa_facebook_alter_empresa_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, default='Sin direccion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default='Argentina', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruta',
            field=models.CharField(blank=True, default='http://gustabin.com/ecommerce/img/', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tituloPagina',
            field=models.CharField(blank=True, default='Carrito de compra', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
