from django.db import models

class Empresa(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=17)
    ciudad = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    pais = models.CharField(default='Argentina', max_length=50)
    logo = models.ImageField(upload_to="empresa", null=True, blank=True, default='sinimagen.png')
    favicon = models.ImageField(upload_to="empresa", null=True, blank=True, default='sinimagen.png')
    tituloPagina = models.CharField(max_length=100, default='Carrito de compra', null=True, blank=True)
    ruta = models.CharField(max_length=150, default='http://gustabin.com/ecommerce/img/', null=True, blank=True)
    subdominio = models.CharField(max_length=100, null=True, blank=True)
    apodo = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    facebook = models.CharField(max_length=100, null=True, blank=True)
    twitter = models.CharField(max_length=100, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    youtube = models.CharField(max_length=100, null=True, blank=True)
    linkedin = models.CharField(max_length=100, null=True, blank=True)
    titulo1 = models.CharField(max_length=100, null=True, blank=True)
    titulo2 = models.CharField(max_length=100, null=True, blank=True)
    titulo3 = models.CharField(max_length=100, null=True, blank=True)
    subtitulo1 = models.CharField(max_length=200, null=True, blank=True)
    subtitulo2 = models.CharField(max_length=200, null=True, blank=True)
    subtitulo3 = models.CharField(max_length=200, null=True, blank=True)
    descripcion1 = models.CharField(max_length=500, null=True, blank=True)
    descripcion2 = models.CharField(max_length=500, null=True, blank=True)
    descripcion3 = models.CharField(max_length=500, null=True, blank=True)
    imagen1 = models.ImageField(upload_to="empresa", null=True, blank=True, default='sinimagen.png')
    imagen2 = models.ImageField(upload_to="empresa", null=True, blank=True,default='sinimagen.png')
    imagen3 = models.ImageField(upload_to="empresa", null=True, blank=True, default='sinimagen.png')
    direccion = models.CharField(max_length=100, default='Sin direccion', null=True, blank=True)
    gateway = models.IntegerField(default=0, choices=((0, 'paypal'), (1, 'Mercadolibre'), (2, 'stripe')))
    environment = models.IntegerField(default=0, choices=((0, 'sandbox'), (1, 'production')))
    sandbox = models.CharField(max_length=80, default='', null=True, blank=True)
    produccion = models.CharField(max_length=80, default='', null=True, blank=True)
    secret = models.CharField(max_length=80, default='', null=True, blank=True)
    accessToken = models.CharField(max_length=80, default='', null=True, blank=True)
    publicaStripe = models.CharField(max_length=110, default='', null=True, blank=True)
    secretaStripe = models.CharField(max_length=110, default='', null=True, blank=True)
    status = models.IntegerField(default=0, choices=((0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')))

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.id)
